plugins {
    id "java"
    id "org.teavm" version "0.15.0"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation teavm.libs.jsoApis
}

teavm {
    wasmGC {
        mainClass = "com.Julian.game.web.WebMain"
        addedToWebApp = true
        targetFileName = "game.wasm"
    }
}
